//RESTAURANT ACTIONS
export const ADD_COUPON = "ADD_COUPON";
export const ADD_COUPON_ERROR = "ADD_COUPON_ERROR";
export const SHOW_RESTAURANT_COUPONS = "SHOW_RESTAURANT_COUPONS";
export const REGISTER_RESTAURANT_FAILURE = "REGISTER_RESTAURANT_FAILURE";
export const REGISTER_RESTAURANT_SUCCESS = "REGISTER_RESTAURANT_SUCCESS";
export const CREATE_RESTAURANT_PROFILE = "CREATE_RESTAURANT_PROFILE";
export const CREATE_RESTAURANT_PROFILE_ERROR =
  "CREATE_RESTAURANT_PROFILE_ERROR";
export const RESTAURANT_LOADED = "RESTAURANT_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const RESTAURANT_LOGIN_ERROR = "RESTAURANT_LOGIN_ERROR";
export const RESTAURANT_LOGGED_IN = "RESTAURANT_LOGGED_IN";
export const LOGOUT_RESTAURANT = "LOGOUT_RESTAURANT";
export const LOAD_RESTAURANT_PROFILE = "LOAD_RESTAURANT_PROFILE";
export const LOAD_RESTAURANT_PROFILE_ERROR = "LOAD_RESTAURANT_PROFILE_ERROR";
export const UPDATE_RESTAURANT_PROFILE = "UPDATE_RESTAURANT_PROFILE";
export const UPDATE_RESTAURANT_PROFILE_ERROR =
  "UPDATE_RESTAURANT_PROFILE_ERROR";

// USER ACTIONS
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";
export const USER_LOADED = "USER_LOADED";
export const BUY_COUPON = "BUY_COUPON";
export const SHOW_USER_COUPONS = "SHOW_USER_COUPONS";
export const SHOW_RESTAURANTS = "SHOW_RESTAURANTS";
export const USER_REGISTER_ERROR = "USER_REGISTER_ERROR";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";
export const LOAD_USER_PROFILE = "LOAD_USER_PROFILE";
export const LOAD_USER_PROFILE_ERROR = "LOAD_USER_PROFILE_ERROR";
export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const LOGOUT_USER = "LOGOUT_USER";
export const ADD_BALANCE = "ADD_BALANCE";
export const ADD_BALANCE_ERROR = "ADD_BALANCE_ERROR";
export const LOAD_USER_ACTIVE_COUPONS = "LOAD_USER_ACTIVE_COUPONS";
export const LOAD_USER_EXPIRED_COUPONS = "LOAD_USER_EXPIRED_COUPONS";
export const LOAD_RESTAURANT_LIST = "LOAD_RESTAURANT_LIST";
